services:
  db:
    image: postgres:16-alpine3.21
    ports:
      - "5433:5432"
    env_file:
      - test.env
    healthcheck: 
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-app:
    build:  
      context: . 
      dockerfile: Dockerfile.test
    env_file:
      - test.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./test-logs:/logs

networks:
  default:
    name: test-network