FROM python:3.12-slim

WORKDIR /app

RUN pip install poetry==2.1.1 && \
    poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root --with test

COPY . .

RUN chmod +x /app/test-entrypoint.sh

ENTRYPOINT ["/app/test-entrypoint.sh"]