services:
  db:
    image: postgres:16-alpine3.21
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck: 
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        
volumes:
  pgdata: