"""initial

Revision ID: bce7fbee8859
Revises: 
Create Date: 2025-07-27 03:46:11.456525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce7fbee8859'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('char_code', sa.String(), nullable=False),
    sa.Column('num_code', sa.Integer(), nullable=False),
    sa.Column('nominal', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('valute_id_prefix', sa.String(), nullable=False),
    sa.Column('min_date', sa.Date(), nullable=False),
    sa.Column('max_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('nominal > 0', name='chk_nominal_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num_code'),
    sa.UniqueConstraint('valute_id_prefix')
    )
    op.create_table('currency_rates',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'currency_id', name='uq_date_currency_id')
    )
    op.create_index(op.f('ix_currency_rates_date'), 'currency_rates', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_rates_date'), table_name='currency_rates')
    op.drop_table('currency_rates')
    op.drop_table('currencies')
    # ### end Alembic commands ###
