"""change currency logic

Revision ID: d3335e6a9e22
Revises: bce7fbee8859
Create Date: 2025-07-27 23:38:47.094335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3335e6a9e22'
down_revision: Union[str, Sequence[str], None] = 'bce7fbee8859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('min_rate', sa.Integer(), nullable=False))
    op.add_column('currencies', sa.Column('max_rate', sa.Integer(), nullable=False))
    op.alter_column('currencies', 'num_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('currencies', 'max_date')
    op.drop_column('currencies', 'min_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('min_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('currencies', sa.Column('max_date', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('currencies', 'num_code',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('currencies', 'max_rate')
    op.drop_column('currencies', 'min_rate')
    # ### end Alembic commands ###
