from typing import Any

CURRENCIES_FOR_SEEDING: list[dict[str, Any]] = [
    {
        "char_code": "AUD",
        "num_code": "036",
        "nominal": 1,
        "name": "Австралийский доллар",
        "valute_id_prefix": "R01010",
        "min_rate": 10,
        "max_rate": 50,
    },
    {
        "char_code": "GBP",
        "num_code": "826",
        "nominal": 1,
        "name": "Фунт стерлингов",
        "valute_id_prefix": "R01035",
        "min_rate": 30,
        "max_rate": 70,
    },
    {
        "char_code": "BYR",
        "num_code": "974",
        "nominal": 1000,
        "name": "Белорусских рублей",
        "valute_id_prefix": "R01090",
        "min_rate": 10,
        "max_rate": 50,
    },
    {
        "char_code": "DKK",
        "num_code": "208",
        "nominal": 10,
        "name": "Датских крон",
        "valute_id_prefix": "R01215",
        "min_rate": 30,
        "max_rate": 70,
    },
    {
        "char_code": "USD",
        "num_code": "840",
        "nominal": 1,
        "name": "Доллар США",
        "valute_id_prefix": "R01235",
        "min_rate": 30,
        "max_rate": 80,
    },
    {
        "char_code": "EUR",
        "num_code": "978",
        "nominal": 1,
        "name": "Евро",
        "valute_id_prefix": "R01239",
        "min_rate": 20,
        "max_rate": 80,
    },
    {
        "char_code": "ISK",
        "num_code": "352",
        "nominal": 100,
        "name": "Исландских крон",
        "valute_id_prefix": "R01310",
        "min_rate": 20,
        "max_rate": 50,
    },
    {
        "char_code": "KZT",
        "num_code": "398",
        "nominal": 100,
        "name": "Тенге",
        "valute_id_prefix": "R01335",
        "min_rate": 15,
        "max_rate": 30,
    },
    {
        "char_code": "CAD",
        "num_code": "124",
        "nominal": 1,
        "name": "Канадский доллар",
        "valute_id_prefix": "R01350",
        "min_rate": 10,
        "max_rate": 40,
    },
    {
        "char_code": "NOK",
        "num_code": "578",
        "nominal": 10,
        "name": "Норвежских крон",
        "valute_id_prefix": "R01535",
        "min_rate": 20,
        "max_rate": 50,
    },
    {
        "char_code": "XDR",
        "num_code": "960",
        "nominal": 1,
        "name": "СДР (специальные права заимствования)",
        "valute_id_prefix": "R01589",
        "min_rate": 30,
        "max_rate": 60,
    },
    {
        "char_code": "SGD",
        "num_code": "702",
        "nominal": 1,
        "name": "Сингапурский доллар",
        "valute_id_prefix": "R01625",
        "min_rate": 10,
        "max_rate": 30,
    },
    {
        "char_code": "TRL",
        "num_code": "792",
        "nominal": 1_000_000,
        "name": "Турецких лир",
        "valute_id_prefix": "R01700",
        "min_rate": 15,
        "max_rate": 30,
    },
    {
        "char_code": "UAH",
        "num_code": "980",
        "nominal": 10,
        "name": "Гривен",
        "valute_id_prefix": "R01720",
        "min_rate": 15,
        "max_rate": 60,
    },
    {
        "char_code": "SEK",
        "num_code": "752",
        "nominal": 10,
        "name": "Шведских крон",
        "valute_id_prefix": "R01770",
        "min_rate": 20,
        "max_rate": 50,
    },
    {
        "char_code": "CHF",
        "num_code": "756",
        "nominal": 1,
        "name": "Швейцарский франк",
        "valute_id_prefix": "R01775",
        "min_rate": 10,
        "max_rate": 40,
    },
    {
        "char_code": "JPY",
        "num_code": "392",
        "nominal": 100,
        "name": "Иен",
        "valute_id_prefix": "R01820",
        "min_rate": 20,
        "max_rate": 50,
    },
]
